name: Publish zkvyper docker image

on:
  workflow_dispatch:
    branches:
      - "main"
    inputs:
      zkvyper_prerelease_ref:
        description: "Version of the `vyper` compiler to build the image with, e.g. 'v0.8.16'"
        type: string
        required: true
      docker_tag:
        description: "Docker tag to push the image to, e.g. 'latest'"
        type: string
        required: false
        default: latest
  workflow_run:
    workflows: [Publish LLVM_runner docker image]
    types: [completed]
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, ci-runner]

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd images/vyper
          gh release -R github.com/matter-labs/compiler-vyper download ${{ inputs.zkvyper_prerelease_ref }} \
          -p '*linux-amd64*' -O ./zkvyper-linux-amd64-musl
          chmod +x ./zkvyper-linux-amd64-musl
          DOCKER_BUILDKIT=1 docker build \
            --no-cache --progress=plain -t matterlabs/zkvyper:${{ inputs.docker_tag }} .
          docker push matterlabs/zkvyper:${{ inputs.docker_tag }}
        env:
          GH_TOKEN: ${{ secrets.ZKSYNC_ADMIN_BOT_ORG_REPO_WRITE }}
